device: cuda:0
model_name: gemma-2
steering_matrix_path: data/steering_matrix/steering_matrix_gemma-2.pt
input_file: data/instructions/test/math_500_sampled.json
batch_size: 8
max_new_tokens: 4096
file_rename: False
prompt_column: problem
strength: -0.5
layers: 20
method: truthflow
epochs: 40