device: cuda:0
model_name: llama3.1
steering_matrix_path: data/steering_matrix/steering_matrix_llama3.1.pt
input_file: data/instructions/test/math_500_sampled.json
batch_size: 8
max_new_tokens: 4096
file_rename: False
prompt_column: problem
strength: -0.5
epochs: 80
layers: 12
method: truthflow